import type { Board } from '../../../../scripts/parity/config';

export type Scenario = 'warm' | 'refreshing' | 'cold-stalled';

const DYNAMIC_TEXT = ['Fresh Label', 'RS Sub'];

const PANEL_STATS: [label: string, stat: string][] = [
  ['Wait for review', 'reviewLatencyHours'],
  ['Coding days', 'codingDays'],
  ['Pipelines', 'pipelines'],
  ['Reciprocity', 'reciprocity'],
  ['MRs merged', 'mrsMerged'],
  ['Size health', 'sizeHealthPct'],
  ['Revert rate', 'revertRate'],
  ['MRs reviewed', 'mrsReviewed'],
  ['Review depth', 'reviewDepth'],
  ['Merge streak', 'longestStreak'],
];

export const BOARDS: Board<Scenario>[] = [
  {
    slug: '01-leaderboard-table',
    frame: 'Leaderboard · Table',
    frameId: 'WqX8t',
    route: '/',
    storage: {
      'forge-view': '"table"',
      'forge-trend': 'false',
      'forge-range': '{"range":"30d"}',
    },
    scenario: 'warm',
    roots: [
      'Crumbs',
      'Top Right',
      'Page Header',
      'Stat Leaders',
      'Standings',
      'Footnote',
    ],
    height: 1000,
    dynamicText: DYNAMIC_TEXT,
  },
  {
    slug: '02-leaderboard-cards',
    frame: 'Leaderboard · Cards',
    frameId: 'iUxSO',
    route: '/',
    storage: { 'forge-view': '"cards"' },
    scenario: 'warm',
    roots: ['Crumbs', 'Top Right', 'Page Header', 'Metric Grid'],
    height: 1400,
    dynamicText: DYNAMIC_TEXT,
  },
  {
    slug: '03-person-stat-detail',
    frame: 'Person · Stat detail',
    frameId: 'bhvvQ',
    route: '/user/srivera/issuesCompleted',
    storage: {},
    scenario: 'warm',
    roots: [
      'Crumbs',
      'Top Right',
      'Back Link',
      'Profile Header',
      'Summary',
      'Body',
    ],
    height: 1300,
    dynamicText: DYNAMIC_TEXT,
  },
  {
    slug: '04-stat-evidence-variants',
    frame: 'Stat detail · evidence variants',
    frameId: 'JPhZn',
    route: '/user/srivera/reviewLatencyHours',
    storage: {},
    scenario: 'warm',
    roots: [],
    height: 1300,
    dynamicText: DYNAMIC_TEXT,
    panels: PANEL_STATS.map(([label, stat]) => ({
      label,
      route: `/user/srivera/${stat}`,
      root: `Panel · ${label}`,
    })),
  },
  {
    slug: '05-refreshing',
    frame: 'Leaderboard · Refreshing',
    frameId: 'k6kFQA',
    route: '/',
    storage: { 'forge-view': '"table"' },
    scenario: 'refreshing',
    roots: [
      'Crumbs',
      'Top Right',
      'Page Header',
      'Refresh Status',
      'Stat Leaders',
      'Standings',
      'Footnote',
    ],
    height: 1100,
    dynamicText: DYNAMIC_TEXT,
    action: {
      kind: 'click',
      layer: 'Refresh Button',
      waitFor: 'Refresh Status',
      until: { layer: 'Fresh Label', pattern: '· \\d{2}s$', timeoutMs: 30_000 },
    },
  },
  {
    slug: '06-first-load-stalled',
    frame: 'Leaderboard · First load, stalled',
    frameId: 'ULlmd',
    route: '/',
    storage: {},
    scenario: 'cold-stalled',
    roots: ['Crumbs', 'Top Right', 'Page Header', 'Refresh Status', 'Skeleton'],
    height: 1000,
    dynamicText: DYNAMIC_TEXT,
    action: {
      kind: 'waitText',
      layer: 'RS Sub',
      until: {
        layer: 'RS Sub',
        pattern: 'still waiting on GitLab',
        timeoutMs: 90_000,
      },
    },
  },
  {
    slug: '07-leaderboard-trend',
    frame: 'Leaderboard · Trend',
    frameId: 'rmvgy',
    route: '/',
    storage: { 'forge-trend': 'true' },
    scenario: 'warm',
    roots: [
      'Crumbs',
      'Top Right',
      'Page Header',
      'Stat Leaders',
      'Standings',
      'Footnote',
    ],
    height: 1000,
    dynamicText: DYNAMIC_TEXT,
  },
];
