declare module '@mattstack/app-kit/icons' {
  interface AppIcons {
    workflow: true;
    layoutDashboard: true;
    fileText: true;
    fileX: true;
    fileCode: true;
    cpu: true;
    circleDot: true;
    replace: true;
    arrowUpRight: true;
    squareTerminal: true;
    minus: true;
    fitView: true;
    panelRight: true;
    panelRightOpen: true;
    wrapText: true;
    gitMerge: true;
    circleCheck: true;
    circleX: true;
    circleSlash: true;
    messageSquare: true;
    messageSquareDiff: true;
    signpost: true;
    circle: true;
    braces: true;
    columns2: true;
    imageOff: true;
    cornerUpLeft: true;
    folder: true;
    gitBranch: true;
    gitPullRequest: true;
    loader: true;
    hand: true;
    bot: true;
    image: true;
    circleAlert: true;
    unplug: true;
    square: true;
    squareCheck: true;
    cornerDownRight: true;
    sparkles: true;
    messagesSquare: true;
    gitCommit: true;
    reply: true;
    circleMinus: true;
  }
}
export {};
