import { lucideWrapperFn, registerIcons } from '@mattstack/app-kit/icons';
// The app's one sanctioned lucide import site, per app-kit's AGENTS.md §8
// registration contract.
// eslint-disable-next-line no-restricted-imports
import {
  ArrowUpRight,
  Bot,
  Braces,
  Building2,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleSlash,
  CircleX,
  Columns2,
  CornerUpLeft,
  Cpu,
  FileCode,
  FileText,
  FileX,
  Folder,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Hand,
  Image as ImageGlyph,
  ImageOff,
  LayoutDashboard,
  Loader,
  Maximize,
  MessageSquare,
  MessageSquareDiff,
  Minus,
  PanelRight,
  PanelRightOpen,
  Replace,
  Signpost,
  SquareTerminal,
  Unplug,
  UsersRound,
  Workflow,
  WrapText,
} from 'lucide-react';

registerIcons({
  workflow: lucideWrapperFn(Workflow),
  layoutDashboard: lucideWrapperFn(LayoutDashboard),
  fileText: lucideWrapperFn(FileText),
  fileX: lucideWrapperFn(FileX),
  fileCode: lucideWrapperFn(FileCode),
  cpu: lucideWrapperFn(Cpu),
  circleDot: lucideWrapperFn(CircleDot),
  replace: lucideWrapperFn(Replace),
  arrowUpRight: lucideWrapperFn(ArrowUpRight),
  squareTerminal: lucideWrapperFn(SquareTerminal),
  minus: lucideWrapperFn(Minus),
  fitView: lucideWrapperFn(Maximize),
  panelRight: lucideWrapperFn(PanelRight),
  panelRightOpen: lucideWrapperFn(PanelRightOpen),
  wrapText: lucideWrapperFn(WrapText),
  gitMerge: lucideWrapperFn(GitMerge),
  circleCheck: lucideWrapperFn(CircleCheck),
  circleX: lucideWrapperFn(CircleX),
  circleSlash: lucideWrapperFn(CircleSlash),
  messageSquare: lucideWrapperFn(MessageSquare),
  messageSquareDiff: lucideWrapperFn(MessageSquareDiff),
  signpost: lucideWrapperFn(Signpost),
  circle: lucideWrapperFn(Circle),
  braces: lucideWrapperFn(Braces),
  columns2: lucideWrapperFn(Columns2),
  imageOff: lucideWrapperFn(ImageOff),
  cornerUpLeft: lucideWrapperFn(CornerUpLeft),
  folder: lucideWrapperFn(Folder),
  gitBranch: lucideWrapperFn(GitBranch),
  gitPullRequest: lucideWrapperFn(GitPullRequest),
  loader: lucideWrapperFn(Loader),
  hand: lucideWrapperFn(Hand),
  bot: lucideWrapperFn(Bot),
  image: lucideWrapperFn(ImageGlyph),
  building: lucideWrapperFn(Building2),
  team: lucideWrapperFn(UsersRound),
  circleAlert: lucideWrapperFn(CircleAlert),
  unplug: lucideWrapperFn(Unplug),
});
