import { stripJsonc } from "./sources.ts";

export type Fragment = {
  extends?: string;
  skills?: { enabled?: string[] };
  pipelines?: Record<string, string[]>;
  bindings?: Record<string, Record<string, string>>;
};

/** label is the layer's provenance name: "default", "base:<pack>", "pack" or "override". */
export type Layer = { label: string; fragment: Fragment };

export type MergedManifest = {
  enabled: string[];
  pipelines: Record<string, string[]>;
  bindings: Record<string, Record<string, string>>;
  provenance: Record<string, string>;
};

export class FragmentError extends Error {}

export function parseFragment(text: string, path: string): Fragment {
  let parsed: unknown;
  try {
    parsed = JSON.parse(stripJsonc(text));
  } catch {
    throw new FragmentError(`fragment is not valid JSONC: ${path}`);
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new FragmentError(`fragment is not a JSON object: ${path}`);
  }
  return parsed as Fragment;
}

export function mergeLayers(layers: Layer[]): MergedManifest {
  const out: MergedManifest = { enabled: [], pipelines: {}, bindings: {}, provenance: {} };
  for (const { label, fragment } of layers) {
    for (const name of fragment.skills?.enabled ?? []) {
      if (!out.enabled.includes(name)) out.enabled.push(name);
    }
    for (const [type, stages] of Object.entries(fragment.pipelines ?? {})) {
      out.pipelines[type] = [...stages];
      out.provenance[`pipeline ${type}`] = label;
    }
    for (const [engineRef, slots] of Object.entries(fragment.bindings ?? {})) {
      for (const [slot, fill] of Object.entries(slots)) {
        (out.bindings[engineRef] ??= {})[slot] = fill;
        out.provenance[`${engineRef} ${slot}`] = label;
      }
    }
  }
  return out;
}

const PROVENANCE_LINE = /^\/\/\s{3}(.+?) <- (\S+)\s*$/;

export function renderManifest(merged: MergedManifest, opts: { repo: string; pack: string }): string {
  const lines = [
    "// GENERATED by rt skills materialize -- do not hand-edit for keeps;",
    "// the next pack install or materialize run rewrites this file.",
    `// repo: ${opts.repo}`,
    `// pack: ${opts.pack}`,
    "// provenance (binding <- layer):",
    ...Object.entries(merged.provenance).map(([key, label]) => `//   ${key} <- ${label}`),
  ];
  const body = { version: 1, skills: { enabled: merged.enabled }, pipelines: merged.pipelines, bindings: merged.bindings };
  return `${lines.join("\n")}\n${JSON.stringify(body, null, 2)}\n`;
}

export function readManifestProvenance(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of text.split("\n")) {
    if (!line.startsWith("//")) break;
    const m = PROVENANCE_LINE.exec(line);
    if (m) out[m[1]!] = m[2]!;
  }
  return out;
}
