import { stripJsonc } from "./sources.ts";

export type Fragment = {
  extends?: string;
  /** A base pack only exists to be named by other packs' `extends`: it never claims a repo and gets no bindings file. */
  base?: boolean;
  skills?: { enabled?: string[] };
  pipelines?: Record<string, string[]>;
  bindings?: Record<string, Record<string, string>>;
};

/** label is the layer's provenance name: "default", "base:<pack>", "pack" or "override". */
export type Layer = { label: string; fragment: Fragment };

export type MergedManifest = {
  enabled: string[];
  pipelines: Record<string, string[]>;
  bindings: Record<string, Record<string, string>>;
  provenance: Record<string, string>;
};

export class FragmentError extends Error {}

function isObject(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function isStringArray(value: unknown): boolean {
  return Array.isArray(value) && value.every((v) => typeof v === "string");
}

function shapeError(doc: Record<string, unknown>): string | null {
  if (doc.extends !== undefined && typeof doc.extends !== "string") return "extends is not a string";
  if (doc.base !== undefined && typeof doc.base !== "boolean") return "base is not a boolean";
  if (doc.skills !== undefined) {
    if (!isObject(doc.skills)) return "skills is not an object";
    if (doc.skills.enabled !== undefined && !isStringArray(doc.skills.enabled)) return "skills.enabled is not an array of strings";
  }
  if (doc.pipelines !== undefined) {
    if (!isObject(doc.pipelines)) return "pipelines is not an object";
    for (const [type, stages] of Object.entries(doc.pipelines)) {
      if (!isStringArray(stages)) return `pipelines.${type} is not an array of strings`;
    }
  }
  if (doc.bindings !== undefined) {
    if (!isObject(doc.bindings)) return "bindings is not an object";
    for (const [engineRef, slots] of Object.entries(doc.bindings)) {
      if (!isObject(slots)) return `bindings.${engineRef} is not an object`;
      // An empty fill is how a later layer unbinds a slot an earlier one filled; compile reads it as unbound.
      for (const [slot, fill] of Object.entries(slots)) {
        if (typeof fill !== "string") return `bindings.${engineRef}.${slot} is not a string`;
      }
    }
  }
  return null;
}

export function parseFragment(text: string, path: string): Fragment {
  let parsed: unknown;
  try {
    parsed = JSON.parse(stripJsonc(text));
  } catch {
    throw new FragmentError(`fragment is not valid JSONC: ${path}`);
  }
  if (!isObject(parsed)) {
    throw new FragmentError(`fragment is not a JSON object: ${path}`);
  }
  const problem = shapeError(parsed);
  if (problem) throw new FragmentError(`fragment ${problem}: ${path}`);
  return parsed as Fragment;
}

export function mergeLayers(layers: Layer[]): MergedManifest {
  // Fragment keys are untrusted: a "__proto__" key assigned into a plain object would write through to Object.prototype.
  const out: MergedManifest = { enabled: [], pipelines: Object.create(null), bindings: Object.create(null), provenance: Object.create(null) };
  for (const { label, fragment } of layers) {
    for (const name of fragment.skills?.enabled ?? []) {
      if (!out.enabled.includes(name)) out.enabled.push(name);
    }
    for (const [type, stages] of Object.entries(fragment.pipelines ?? {})) {
      out.pipelines[type] = [...stages];
      out.provenance[`pipeline ${type}`] = label;
    }
    for (const [engineRef, slots] of Object.entries(fragment.bindings ?? {})) {
      for (const [slot, fill] of Object.entries(slots)) {
        (out.bindings[engineRef] ??= Object.create(null) as Record<string, string>)[slot] = fill;
        out.provenance[`${engineRef} ${slot}`] = label;
      }
    }
  }
  return out;
}

const PROVENANCE_LINE = /^\/\/\s{3}(.+?) <- (\S+)\s*$/;

export function renderManifest(merged: MergedManifest, opts: { repo: string; pack: string }): string {
  const lines = [
    "// GENERATED by rt skills materialize -- do not hand-edit for keeps;",
    "// the next pack install or materialize run rewrites this file.",
    `// repo: ${opts.repo}`,
    `// pack: ${opts.pack}`,
    "// provenance (binding <- layer):",
    ...Object.entries(merged.provenance).map(([key, label]) => `//   ${key} <- ${label}`),
  ];
  const body = { version: 1, skills: { enabled: merged.enabled }, pipelines: merged.pipelines, bindings: merged.bindings };
  return `${lines.join("\n")}\n${JSON.stringify(body, null, 2)}\n`;
}

export function readManifestProvenance(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of text.split("\n")) {
    if (!line.startsWith("//")) break;
    const m = PROVENANCE_LINE.exec(line);
    if (m) out[m[1]!] = m[2]!;
  }
  return out;
}
