import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, spyOn, test } from 'bun:test';

import { parseConfig } from '../config.ts';
import {
  packForLaunch,
  resolveBoardSkill,
  resolveLaunchSkill,
} from '../manifest-bindings.ts';

const base = {
  gitlabHost: 'https://gitlab.com',
  projects: ['org/repo'],
  members: [{ username: 'alice' }],
  doctorSkill: 'config:doctor',
};

const cfg = parseConfig(JSON.stringify(base));

/** A fresh mkdtemp mattstackHome with `repos/<slug>/packs/<pack>/skills.jsonc`
    written from `contents`, or no `repos` dir at all when `slug` is null. */
function makeHome(
  slug: string | null,
  pack: string,
  contents?: string
): string {
  const home = mkdtempSync(join(tmpdir(), 'manifest-bindings-home-'));
  if (slug !== null) {
    const packDir = join(home, 'repos', slug, 'packs', pack);
    mkdirSync(packDir, { recursive: true });
    writeFileSync(join(packDir, 'skills.jsonc'), contents ?? '');
  }
  return home;
}

const widgetsReview = JSON.stringify({
  bindings: { 'board:review': { review: 'widgets:review' } },
});

describe('resolveBoardSkill', () => {
  test('tab pack -> that pack file', () => {
    const home = makeHome('gitlab.com-org-repo', 'widgets', widgetsReview);
    expect(
      resolveBoardSkill('review', 'org/repo', cfg, 'widgets', home)
    ).toEqual({ skill: 'widgets:review', source: 'manifest', pack: 'widgets' });
  });

  test('no pack -> config fallback, pack null', () => {
    const home = makeHome('gitlab.com-org-repo', 'widgets', widgetsReview);
    expect(resolveBoardSkill('review', 'org/repo', cfg, null, home)).toEqual({
      skill: '',
      source: 'config',
      pack: null,
    });
  });

  test('a pack with no board:review binding -> config fallback, pack kept', () => {
    const home = makeHome(
      'gitlab.com-org-repo',
      'widgets',
      JSON.stringify({ bindings: {} })
    );
    expect(
      resolveBoardSkill('review', 'org/repo', cfg, 'widgets', home)
    ).toEqual({ skill: '', source: 'config', pack: 'widgets' });
  });

  test('a pack other than the one on disk -> config fallback', () => {
    const home = makeHome('gitlab.com-org-repo', 'widgets', widgetsReview);
    expect(
      resolveBoardSkill('review', 'org/repo', cfg, 'gadgets', home)
    ).toEqual({ skill: '', source: 'config', pack: 'gadgets' });
  });

  test('the old repos/<slug>/skills.jsonc is never read', () => {
    const home = mkdtempSync(join(tmpdir(), 'mb-'));
    mkdirSync(join(home, 'repos', 'gitlab.com-org-repo'), { recursive: true });
    writeFileSync(
      join(home, 'repos', 'gitlab.com-org-repo', 'skills.jsonc'),
      JSON.stringify({ bindings: { 'board:review': { review: 'old:review' } } })
    );
    expect(
      resolveBoardSkill('review', 'org/repo', cfg, 'widgets', home).skill
    ).toBe('');
  });

  test('no repos dir -> doctor config fallback', () => {
    const home = makeHome(null, 'widgets');
    expect(
      resolveBoardSkill('doctor', 'org/repo', cfg, 'widgets', home)
    ).toEqual({ skill: 'config:doctor', source: 'config', pack: 'widgets' });
  });

  test('malformed pack file -> config fallback (no throw)', () => {
    const home = makeHome('gitlab.com-org-repo', 'widgets', '{ not valid json');
    expect(
      resolveBoardSkill('doctor', 'org/repo', cfg, 'widgets', home)
    ).toEqual({ skill: 'config:doctor', source: 'config', pack: 'widgets' });
  });

  test('absent key in an otherwise valid pack file -> config fallback', () => {
    const home = makeHome('gitlab.com-org-repo', 'widgets', widgetsReview);
    expect(
      resolveBoardSkill('doctor', 'org/repo', cfg, 'widgets', home)
    ).toEqual({ skill: 'config:doctor', source: 'config', pack: 'widgets' });
  });

  test('empty skill string in binding -> config fallback', () => {
    const home = makeHome(
      'gitlab.com-org-repo',
      'widgets',
      JSON.stringify({ bindings: { 'board:review': { review: '' } } })
    );
    expect(
      resolveBoardSkill('review', 'org/repo', cfg, 'widgets', home).source
    ).toBe('config');
  });

  test('a provenance header parses', () => {
    const home = makeHome(
      'gitlab.com-org-repo',
      'widgets',
      [
        '// GENERATED by rt skills materialize -- do not hand-edit for keeps;',
        '// repo: gitlab.com/org/repo',
        '// pack: widgets',
        '// provenance (binding <- layer):',
        '//   board:doctor <- pack',
        '{',
        '  "bindings": {',
        '    "board:doctor": { "doctor": "widgets:doctor" }',
        '  }',
        '}',
        '',
      ].join('\n')
    );
    expect(
      resolveBoardSkill('doctor', 'org/repo', cfg, 'widgets', home)
    ).toEqual({ skill: 'widgets:doctor', source: 'manifest', pack: 'widgets' });
  });

  test('slug derivation: host + project path locate repos/<host>-<project>/packs/<pack>', () => {
    const home = makeHome(
      'gitlab.example.com-acme-widgets',
      'widgets',
      widgetsReview
    );
    const exampleCfg = parseConfig(
      JSON.stringify({ ...base, gitlabHost: 'https://gitlab.example.com' })
    );
    expect(
      resolveBoardSkill('review', 'acme/widgets', exampleCfg, 'widgets', home)
        .skill
    ).toBe('widgets:review');
  });

  test('trailing-slash and credentialed hosts resolve the same pack file', () => {
    const home = makeHome('gitlab.com-org-repo', 'widgets', widgetsReview);
    for (const gitlabHost of [
      'https://gitlab.com/',
      'https://user:pass@gitlab.com',
    ]) {
      const hostCfg = parseConfig(JSON.stringify({ ...base, gitlabHost }));
      expect(
        resolveBoardSkill('review', 'org/repo', hostCfg, 'widgets', home).skill
      ).toBe('widgets:review');
    }
  });
});

describe('packForLaunch', () => {
  test('tab pack, then defaultPack, then null', () => {
    const withTabs = parseConfig(
      JSON.stringify({
        ...base,
        defaultPack: 'gadgets',
        tabs: [
          { id: 'w', label: 'W', source: { kind: 'authors' }, pack: 'widgets' },
          { id: 'g', label: 'G', source: { kind: 'authors' } },
        ],
      })
    );
    expect(packForLaunch(withTabs, 'w')).toBe('widgets');
    expect(packForLaunch(withTabs, 'g')).toBe('gadgets');
    expect(packForLaunch(withTabs, undefined)).toBe('gadgets');
    expect(
      packForLaunch(parseConfig(JSON.stringify(base)), undefined)
    ).toBeNull();
  });
});

describe('resolveLaunchSkill', () => {
  const mrUrl = 'https://gitlab.com/org/repo/-/merge_requests/7';
  let logs: string[];
  let logSpy: ReturnType<typeof spyOn>;

  beforeEach(() => {
    logs = [];
    logSpy = spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      logs.push(args.join(' '));
    });
  });
  afterEach(() => {
    logSpy.mockRestore();
  });

  test('a pack binding resolves from the MR webUrl and logs the pack', () => {
    const home = makeHome('gitlab.com-org-repo', 'widgets', widgetsReview);
    expect(resolveLaunchSkill('review', mrUrl, cfg, 'widgets', home)).toBe(
      'widgets:review'
    );
    expect(logs).toEqual([
      'review skill: widgets:review (manifest, pack widgets)',
    ]);
  });

  test('no pack -> generic skill, and the log says so', () => {
    const home = makeHome('gitlab.com-org-repo', 'widgets', widgetsReview);
    expect(resolveLaunchSkill('review', mrUrl, cfg, null, home)).toBe('');
    expect(logs).toEqual(['review skill:  (config, no pack)']);
  });

  test('a pack with no board:review binding -> generic skill, never a throw', () => {
    const home = makeHome(
      'gitlab.com-org-repo',
      'widgets',
      JSON.stringify({ bindings: {} })
    );
    expect(resolveLaunchSkill('review', mrUrl, cfg, 'widgets', home)).toBe('');
    expect(logs).toEqual(['review skill:  (config, pack widgets)']);
  });

  test('an unparseable MR url -> config fallback with the pack kept', () => {
    const home = makeHome('gitlab.com-org-repo', 'widgets', widgetsReview);
    expect(
      resolveLaunchSkill('doctor', 'not a url', cfg, 'widgets', home)
    ).toBe('config:doctor');
    expect(logs).toEqual([
      'doctor skill: config:doctor (config, pack widgets)',
    ]);
  });
});
