import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  start: [{ type: "autogenerated", dirName: "start" }],
  apps: [{ type: "autogenerated", dirName: "apps" }],
  rt: [{ type: "autogenerated", dirName: "rt" }],
  gitq: [{ type: "autogenerated", dirName: "gitq" }],
  skills: [{ type: "autogenerated", dirName: "skills" }],
};

export default sidebars;
